# ── Motor ModSecurity ─────────────────────────────────────
SecRuleEngine On

# ── Body de peticiones ────────────────────────────────────
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072

# ── Respuestas ────────────────────────────────────────────
SecResponseBodyAccess On
SecResponseBodyLimit 524288

# ── Logs ──────────────────────────────────────────────────
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLog /var/log/apache2/modsec_audit.log
SecAuditLogParts ABIJDEFHZ

# ── Datos temporales ──────────────────────────────────────
SecTmpDir /tmp/
SecDataDir /tmp/