services:
  angular:
    container_name: Angular
    build:
      context: ..
      dockerfile: setup/Dockerfile.prod
      target: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt/live/frontend-infernum-original.duckdns.org-0001:/etc/letsencrypt/live/frontend-infernum-original.duckdns.org:ro"
      - "/etc/letsencrypt/archive/frontend-infernum-original.duckdns.org-0001:/etc/letsencrypt/archive/frontend-infernum-original.duckdns.org:ro"
    restart: unless-stopped
